[package]
name = "actix-web-tokio-scheduler-example"
version = "0.1.0"
authors = ["itok01 <contact@itok01.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
tokio = "0.2"
